### PR TITLE
Add a serialiser that orders dictionary keys alphabetically.

### PR DESCRIPTION
**Pull request by elland**
Not completely sure whether this belongs here or not, but I think it should be in one of our modules.

This is very useful for signing parameters before submitting to a secure server.

### CODE REVIEW

**Comment by elland** [comment]
Is it possible to re-trigger the CI stuff?

**Comment by 3lvis** [comment]
@Elland first you need to rebase with master.

**Comment by elland** [comment]
👍

**Comment by elland** [comment]
I'll merge this then.

**Comment by 3lvis** [comment]
Why are you adding this method? I can't remember

**Comment by elland** [comment]
@3lvis from the description:

>  signing parameters before submitting to a secure server

**Comment by 3lvis** [comment]
@Elland Please add it to the README :)

**Comment by elland** [comment]
👏 good idea.

**Pull request merged**
