### PR TITLE
Added optional collection element retrieval.

### PR DESCRIPTION
**Pull request by elland**

### CODE REVIEW

**Comment by 3lvis** [comment]
I like something like this better:

http://ericasadun.com/2015/06/01/swift-safe-array-indexing-my-favorite-thing-of-the-new-week/

**Comment by 3lvis** [comment]
Meaning using subscripts

**Comment by elland** [comment]
Then why merge? 🤔

**Comment by 3lvis** [comment]
You merged 😂

**Comment by elland** [comment]
😭 😂

**Pull request merged**
